spring:
  h2:
    console:
      enable: true
      path: /h2-console

#  sql:
#    init:
#      mode: always

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
#    data: classpath:db/h2/data.sql
#    schema: classpath:db/h2/schema.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: ture